import { CarbonRule, ScoreGroup } from './types';

const DEVICE_ENERGY: ScoreGroup = 'Device Energy';
const NETWORK_CLOUD: ScoreGroup = 'Network & Cloud';
const AUDIO: ScoreGroup = 'Audio';
const BEHAVIORAL: ScoreGroup = 'Behavioral';
const CHARGING: ScoreGroup = 'Charging';
const PROCESSING: ScoreGroup = 'Processing & Sensors';

export const thresholds = {
  locationRequests: 40,
  autoplayVideosCount: 6,
  multiDeviceSyncEvents: 5,
  duplicateMedia: 35,
  compressionTasks: 3,
  heavyAppOpens: 7,
  batteryExtremeMinutes: 180,
  gyroActiveApps: 3,
  radioHighPowerTime: 45,
};

const rule = (definition: CarbonRule) => definition;

export const carbonRules: CarbonRule[] = [
  rule({
    id: 'brightness_high',
    category: 'Brightness',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.avgBrightness > 0.8,
    notification: 'Screen brightness was high today — displays consume significant power at high levels.',
    recommendation: 'Keep brightness near 40–60% for best efficiency.',
    source: 'Source: IEEE Display Power Studies',
    scoreImpact: -4,
    summary: 'High brightness pushed display power up.',
    referenceId: 'ieee-display-power',
  }),
  rule({
    id: 'brightness_positive',
    category: 'Brightness',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.avgBrightness < 0.5,
    notification: 'Your brightness level stayed efficient today.',
    recommendation: 'This helps significantly reduce energy use.',
    source: 'Source: IEEE Display Power Studies',
    scoreImpact: 2,
    summary: 'Efficient brightness reduced display demand.',
    referenceId: 'ieee-display-power',
  }),
  rule({
    id: 'screen_time_high',
    category: 'Screen Time',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.screenTime > 180,
    notification: 'High screen time increases device energy use.',
    recommendation: 'Short breaks help reduce power consumption.',
    source: 'Source: The Shift Project',
    scoreImpact: -4,
    summary: 'Long active use lifted device energy demand.',
    referenceId: 'shift-project',
  }),
  rule({
    id: 'screen_time_positive',
    category: 'Screen Time',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.screenTime < 90,
    notification: 'Your screen time was balanced today.',
    recommendation: 'Mindful use reduces digital emissions.',
    source: 'Source: The Shift Project',
    scoreImpact: 2,
    summary: 'Balanced screen time kept daily emissions lighter.',
    referenceId: 'shift-project',
  }),
  rule({
    id: 'idle_screen_on_high',
    category: 'Idle Screen-On',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.idleScreenOn > 20,
    notification: 'The screen stayed on while inactive.',
    recommendation: 'Tap power before putting the phone down.',
    source: 'Source: Apple Battery Guidelines',
    scoreImpact: -2,
    summary: 'Idle screen-on time added avoidable drain.',
    referenceId: 'apple-battery',
  }),
  rule({
    id: 'phone_temperature_high',
    category: 'Phone Temperature',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.avgTemp > 38,
    notification: 'Your phone ran warm, increasing power draw.',
    recommendation: 'Avoid heavy use in hot environments.',
    source: 'Source: Battery University',
    scoreImpact: -3,
    summary: 'Heat raised energy loss and battery stress.',
    referenceId: 'battery-university',
  }),
  rule({
    id: 'phone_temperature_positive',
    category: 'Phone Temperature',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.avgTemp < 35,
    notification: 'Healthy device temperature today.',
    recommendation: 'Balanced device load conserves energy.',
    source: 'Source: Battery University',
    scoreImpact: 1,
    summary: 'Cooler operating temperature supported efficient performance.',
    referenceId: 'battery-university',
  }),
  rule({
    id: 'bluetooth_usage_high',
    category: 'Bluetooth Usage',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.btOnTime > 8 && metrics.btActiveDevices === 0,
    notification: 'Bluetooth stayed on with no connected devices.',
    recommendation: 'Turn it off when unused.',
    source: 'Source: Mobile Wireless Power Profiling (ACM)',
    scoreImpact: -1,
    summary: 'Inactive Bluetooth time created unnecessary radio use.',
    referenceId: 'acm-wireless-power',
  }),
  rule({
    id: 'bluetooth_usage_positive',
    category: 'Bluetooth Usage',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.btOnTime < 2,
    notification: 'Bluetooth usage stayed efficient today.',
    recommendation: 'Limiting unused radios saves energy.',
    source: 'Source: Mobile Wireless Power Profiling (ACM)',
    scoreImpact: 1,
    summary: 'Short Bluetooth use kept radio power low.',
    referenceId: 'acm-wireless-power',
  }),
  rule({
    id: 'location_polling_high',
    category: 'Location Polling',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.locationRequests > thresholds.locationRequests,
    notification: 'Apps requested your location frequently.',
    recommendation: 'Use ‘While Using App’ permissions.',
    source: 'Source: Android Location Battery Docs',
    scoreImpact: -3,
    summary: 'Frequent location checks added background battery work.',
    referenceId: 'android-location',
  }),
  rule({
    id: 'location_polling_positive',
    category: 'Location Polling',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.locationAlwaysOnApps === 0,
    notification: 'Location access remained minimal.',
    recommendation: 'This greatly reduces background battery drain.',
    source: 'Source: Android Location Battery Docs',
    scoreImpact: 1,
    summary: 'No always-on location apps kept background drain down.',
    referenceId: 'android-location',
  }),
  rule({
    id: 'hotspot_usage_high',
    category: 'Hotspot Usage',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.hotspotDuration > 10,
    notification: 'Hotspot was active — this consumes significant power.',
    recommendation: 'Disable hotspot when finished.',
    source: 'Source: Smartphone Tethering Energy Studies',
    scoreImpact: -4,
    summary: 'Hotspot time materially increased radio and battery load.',
    referenceId: 'tethering-energy',
  }),
  rule({
    id: 'sleep_mode_drain_high',
    category: 'Sleep-mode Drain',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.sleepEnergy > metrics.sleepBaseline * 1.5,
    notification: 'Your device consumed more energy than normal while sleeping.',
    recommendation: 'Reduce background sync at night.',
    source: 'Source: Mobile Standby Energy Profiles (IEEE)',
    scoreImpact: -2,
    summary: 'Nighttime standby used more energy than expected.',
    referenceId: 'standby-energy',
  }),
  rule({
    id: 'sleep_mode_drain_positive',
    category: 'Sleep-mode Drain',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.sleepEnergy <= metrics.sleepBaseline,
    notification: 'Low overnight energy consumption.',
    recommendation: 'Optimized background behavior saves energy.',
    source: 'Source: Mobile Standby Energy Profiles (IEEE)',
    scoreImpact: 1,
    summary: 'Overnight standby stayed lean and efficient.',
    referenceId: 'standby-energy',
  }),
  rule({
    id: 'background_processes_high',
    category: 'Background Processes',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.backgroundActiveApps > 10,
    notification: 'Many apps ran in the background.',
    recommendation: 'Limit background refresh.',
    source: 'Source: Apple Developer Docs',
    scoreImpact: -3,
    summary: 'Background activity kept the device busy off-screen.',
    referenceId: 'apple-developer-background',
  }),
  rule({
    id: 'background_processes_positive',
    category: 'Background Processes',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.backgroundActiveApps <= 3,
    notification: 'Minimal background activity today.',
    recommendation: 'Efficient setup!',
    source: 'Source: Apple Developer Docs',
    scoreImpact: 1,
    summary: 'Minimal background tasks supported a calmer power profile.',
    referenceId: 'apple-developer-background',
  }),
  rule({
    id: 'widgets_live_activities_high',
    category: 'Widgets & Live Activities',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.widgetCount >= 5,
    notification: 'Many widgets increase refresh energy.',
    recommendation: 'Keep only the essentials.',
    source: 'Source: ACM Mobile UX Power Studies',
    scoreImpact: -2,
    summary: 'Frequent widget refreshes increased background work.',
    referenceId: 'acm-mobile-ux',
  }),
  rule({
    id: 'widgets_live_activities_positive',
    category: 'Widgets & Live Activities',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.widgetCount <= 2,
    notification: 'Light home screen setup.',
    recommendation: 'This reduces background work.',
    source: 'Source: ACM Mobile UX Power Studies',
    scoreImpact: 1,
    summary: 'A lighter home screen reduced refresh overhead.',
    referenceId: 'acm-mobile-ux',
  }),
  rule({
    id: 'live_wallpapers_high',
    category: 'Live Wallpapers',
    group: DEVICE_ENERGY,
    trigger: (metrics) => metrics.liveWallpaperEnabled,
    notification: 'Live wallpapers use GPU power continuously.',
    recommendation: 'Prefer static backgrounds for efficiency.',
    source: 'Source: GPU Power Profiling Research',
    scoreImpact: -2,
    summary: 'Animated backgrounds kept graphics work active.',
    referenceId: 'gpu-power',
  }),
  rule({
    id: 'mobile_data_usage_high',
    category: 'Mobile Data Usage',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.mobileDataUsage > 500,
    notification: 'High mobile data usage increases network energy.',
    recommendation: 'Prefer Wi-Fi for large transfers.',
    source: 'Source: Ericsson Mobility Report',
    scoreImpact: -3,
    summary: 'High cellular data volume increased network energy.',
    referenceId: 'ericsson-mobility',
  }),
  rule({
    id: 'mobile_data_usage_positive',
    category: 'Mobile Data Usage',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.mobileDataUsage < 100,
    notification: 'Very efficient mobile usage today.',
    recommendation: 'Wi-Fi usage reduces cellular power load.',
    source: 'Source: Ericsson Mobility Report',
    scoreImpact: 1,
    summary: 'Low cellular data kept radio energy in check.',
    referenceId: 'ericsson-mobility',
  }),
  rule({
    id: 'high_data_streaming_high',
    category: 'High-Data Streaming',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.videoStreamingTime > 60,
    notification: 'Online video has the highest digital carbon footprint.',
    recommendation: 'Lower resolution or shorter sessions help.',
    source: 'Source: The Shift Project',
    scoreImpact: -5,
    summary: 'Streaming time dominated today’s network-related footprint.',
    referenceId: 'shift-project',
  }),
  rule({
    id: 'high_data_streaming_positive',
    category: 'High-Data Streaming',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.videoStreamingTime < 20,
    notification: 'Low video streaming today.',
    recommendation: 'This significantly reduces data-related emissions.',
    source: 'Source: The Shift Project',
    scoreImpact: 2,
    summary: 'Limited streaming sharply reduced data emissions.',
    referenceId: 'shift-project',
  }),
  rule({
    id: 'large_mobile_transfers_high',
    category: 'Large Mobile Transfers',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.largeMobileTransfers > 200,
    notification: 'Large files were downloaded over mobile data.',
    recommendation: 'Use Wi-Fi for big transfers.',
    source: 'Source: IEA',
    scoreImpact: -2,
    summary: 'Large downloads over cellular added unnecessary network load.',
    referenceId: 'iea-data-centres',
  }),
  rule({
    id: 'cloud_sync_bursts_high',
    category: 'Cloud Sync Bursts',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.cloudSyncSessions > 3,
    notification: 'Multiple cloud sync operations occurred.',
    recommendation: 'Reduce sync frequency where possible.',
    source: 'Source: IEA Datacenter Reports',
    scoreImpact: -3,
    summary: 'Repeated syncs increased cloud and network overhead.',
    referenceId: 'iea-data-centres',
  }),
  rule({
    id: 'cloud_sync_bursts_positive',
    category: 'Cloud Sync Bursts',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.cloudSyncSessions === 1,
    notification: 'Efficient cloud sync today.',
    recommendation: 'Single daily sync is optimal.',
    source: 'Source: IEA Datacenter Reports',
    scoreImpact: 1,
    summary: 'A single sync kept infrastructure demand efficient.',
    referenceId: 'iea-data-centres',
  }),
  rule({
    id: 'autoplay_high',
    category: 'Auto-play',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.autoplayVideosCount > thresholds.autoplayVideosCount,
    notification: 'Auto-play started unnecessary videos.',
    recommendation: 'Disable auto-play to reduce data load.',
    source: 'Source: The Shift Project',
    scoreImpact: -2,
    summary: 'Autoplay spun up avoidable data-heavy sessions.',
    referenceId: 'shift-project',
  }),
  rule({
    id: 'updates_on_mobile_high',
    category: 'Updates on Mobile',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.mobileUpdatesData > 100,
    notification: 'App updates ran over mobile data.',
    recommendation: 'Keep updates on Wi-Fi only.',
    source: 'Source: Apple Developer Docs',
    scoreImpact: -2,
    summary: 'Mobile updates added avoidable cellular transfer load.',
    referenceId: 'apple-developer-background',
  }),
  rule({
    id: 'vpn_high',
    category: 'VPN',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.vpnUsageTime > 60,
    notification: 'VPN adds extra network hops.',
    recommendation: 'Use only when needed.',
    source: 'Source: Network Routing Power Studies',
    scoreImpact: -2,
    summary: 'Extended VPN time lengthened routing overhead.',
    referenceId: 'routing-power',
  }),
  rule({
    id: 'weak_signal_high',
    category: 'Weak Signal',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.lowSignalTime > 60,
    notification: 'Your device stayed in low-signal mode.',
    recommendation: 'Use Wi-Fi in weak signal areas.',
    source: 'Source: Mobile Radio Energy Papers',
    scoreImpact: -3,
    summary: 'Low signal pushed the modem into higher power states.',
    referenceId: 'mobile-radio-energy',
  }),
  rule({
    id: 'weak_signal_positive',
    category: 'Weak Signal',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.lowSignalTime === 0,
    notification: 'Strong connection all day.',
    recommendation: 'Stable signal reduces radio power.',
    source: 'Source: Mobile Radio Energy Papers',
    scoreImpact: 1,
    summary: 'Stable connection avoided high-power modem behavior.',
    referenceId: 'mobile-radio-energy',
  }),
  rule({
    id: 'multi_device_sync_high',
    category: 'Multi-Device Sync',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.multiDeviceSyncEvents > thresholds.multiDeviceSyncEvents,
    notification: 'Your data synced across multiple devices.',
    recommendation: 'Disable real-time sync on non-primary devices.',
    source: 'Source: IEA Cloud Studies',
    scoreImpact: -2,
    summary: 'Cross-device sync multiplied cloud activity.',
    referenceId: 'iea-data-centres',
  }),
  rule({
    id: 'auto_backup_frequency_high',
    category: 'Auto-backup Frequency',
    group: NETWORK_CLOUD,
    trigger: (metrics) => metrics.backupRunsPerDay > 1,
    notification: 'Multiple backups ran today.',
    recommendation: 'One scheduled backup is sufficient.',
    source: 'Source: Cloud Energy Reports',
    scoreImpact: -2,
    summary: 'Repeated backups increased transfer and storage work.',
    referenceId: 'iea-data-centres',
  }),
  rule({
    id: 'speakerphone_high',
    category: 'Speakerphone',
    group: AUDIO,
    trigger: (metrics) => metrics.speakerCallTime > 5,
    notification: 'Speakerphone uses more amplifier power.',
    recommendation: 'Use earpiece or wired audio for long calls.',
    source: 'Source: Audio Amplifier Energy Studies',
    scoreImpact: -2,
    summary: 'Speaker mode drew extra amplifier power.',
    referenceId: 'audio-amplifier',
  }),
  rule({
    id: 'speakerphone_positive',
    category: 'Speakerphone',
    group: AUDIO,
    trigger: (metrics) => metrics.speakerCallTime === 0,
    notification: 'Great — no speakerphone use today.',
    recommendation: 'This saves extra audio power.',
    source: 'Source: Audio Amplifier Energy Studies',
    scoreImpact: 1,
    summary: 'Skipping speakerphone kept audio load lighter.',
    referenceId: 'audio-amplifier',
  }),
  rule({
    id: 'high_volume_music_high',
    category: 'High-Volume Music',
    group: AUDIO,
    trigger: (metrics) => metrics.avgMusicVolume > 0.7,
    notification: 'Music was played at high volume.',
    recommendation: 'Lowering volume reduces amplifier power draw.',
    source: 'Source: Audio Hardware Profiling',
    scoreImpact: -2,
    summary: 'High playback volume increased amplifier demand.',
    referenceId: 'audio-amplifier',
  }),
  rule({
    id: 'high_volume_music_positive',
    category: 'High-Volume Music',
    group: AUDIO,
    trigger: (metrics) => metrics.avgMusicVolume < 0.4,
    notification: 'Efficient listening volume today.',
    recommendation: 'Moderate audio levels are energy-friendly.',
    source: 'Source: Audio Hardware Profiling',
    scoreImpact: 1,
    summary: 'Moderate volume kept audio power efficient.',
    referenceId: 'audio-amplifier',
  }),
  rule({
    id: 'long_music_sessions_high',
    category: 'Long Music Sessions',
    group: AUDIO,
    trigger: (metrics) => metrics.musicListeningTime > 90,
    notification: 'Long listening sessions increase energy use.',
    recommendation: 'Short breaks help.',
    source: 'Source: Audio Energy Reports',
    scoreImpact: -2,
    summary: 'Extended music time added steady playback energy.',
    referenceId: 'audio-amplifier',
  }),
  rule({
    id: 'long_calls_high',
    category: 'Long Calls',
    group: AUDIO,
    trigger: (metrics) => metrics.singleCallDuration > 20,
    notification: 'Long calls require sustained modem + audio power.',
    recommendation: 'Shorter calls reduce load.',
    source: 'Source: Telephony Energy Research',
    scoreImpact: -2,
    summary: 'One long call kept modem and audio systems active.',
    referenceId: 'telephony-energy',
  }),
  rule({
    id: 'frequent_call_bursts_high',
    category: 'Frequent Call Bursts',
    group: AUDIO,
    trigger: (metrics) => metrics.callCount > 10,
    notification: 'Many calls today increased radio activity.',
    recommendation: 'Combine conversations where possible.',
    source: 'Source: Mobile Radio Papers',
    scoreImpact: -1,
    summary: 'Many short calls caused repeated radio wakeups.',
    referenceId: 'telephony-energy',
  }),
  rule({
    id: 'bluetooth_audio_high',
    category: 'Bluetooth Audio',
    group: AUDIO,
    trigger: (metrics) => metrics.btAudioTime > 60,
    notification: 'Bluetooth audio was active for long periods.',
    recommendation: 'Wired audio can be more energy-efficient.',
    source: 'Source: Wireless Audio Studies',
    scoreImpact: -1,
    summary: 'Long Bluetooth listening extended radio audio load.',
    referenceId: 'acm-wireless-power',
  }),
  rule({
    id: 'social_media_time_high',
    category: 'Social Media Time',
    group: BEHAVIORAL,
    trigger: (metrics) => metrics.socialMediaTime > 90,
    notification: 'High social media use increases data & display power.',
    recommendation: 'Short breaks help lower digital emissions.',
    source: 'Source: Digital Wellbeing Emission Research',
    scoreImpact: -3,
    summary: 'Long social sessions amplified screen and network usage.',
    referenceId: 'digital-wellbeing',
  }),
  rule({
    id: 'social_media_time_positive',
    category: 'Social Media Time',
    group: BEHAVIORAL,
    trigger: (metrics) => metrics.socialMediaTime < 30,
    notification: 'Low social media use today.',
    recommendation: 'Helps reduce unnecessary data usage.',
    source: 'Source: Digital Wellbeing Emission Research',
    scoreImpact: 2,
    summary: 'Low social media time kept the day digitally lighter.',
    referenceId: 'digital-wellbeing',
  }),
  rule({
    id: 'notification_bursts_high',
    category: 'Notification Bursts',
    group: BEHAVIORAL,
    trigger: (metrics) => metrics.notificationsPerDay > 120,
    notification: 'Frequent notifications woke your screen often.',
    recommendation: 'Mute non-essential apps.',
    source: 'Source: Mobile UX Battery Studies',
    scoreImpact: -2,
    summary: 'Repeated notifications increased wakeups and screen checks.',
    referenceId: 'acm-mobile-ux',
  }),
  rule({
    id: 'short_trip_vehicle_behavior_high',
    category: 'Short-Trip Vehicle Behavior',
    group: BEHAVIORAL,
    trigger: (metrics) => metrics.shortVehicleTrips > 1,
    notification: 'Short trips could be walked or cycled.',
    recommendation: 'Active transport cuts emissions significantly.',
    source: 'Source: European Environment Agency',
    scoreImpact: -3,
    summary: 'Short car trips carried a disproportionately high footprint.',
    referenceId: 'eea-transport',
  }),
  rule({
    id: 'low_movement_high',
    category: 'Low Movement',
    group: BEHAVIORAL,
    trigger: (metrics) => metrics.steps < 2000,
    notification: 'Today had low movement.',
    recommendation: 'Short walks can replace short car trips.',
    source: 'Source: EEA',
    scoreImpact: -1,
    summary: 'Low movement reduced chances to replace short vehicle trips.',
    referenceId: 'eea-transport',
  }),
  rule({
    id: 'unused_apps_high',
    category: 'Unused Apps',
    group: BEHAVIORAL,
    trigger: (metrics) => metrics.unusedAppsCount > 10,
    notification: 'Unused apps increase background scanning & updates.',
    recommendation: 'Delete apps you no longer use.',
    source: 'Source: App Lifecycle Battery Docs',
    scoreImpact: -2,
    summary: 'Unused apps still contributed background maintenance work.',
    referenceId: 'app-lifecycle',
  }),
  rule({
    id: 'digital_clutter_high',
    category: 'Digital Clutter',
    group: BEHAVIORAL,
    trigger: (metrics) => metrics.duplicateMedia > thresholds.duplicateMedia,
    notification: 'Large or duplicate files increase sync & indexing.',
    recommendation: 'Clean media storage occasionally.',
    source: 'Source: Storage Indexing Papers',
    scoreImpact: -2,
    summary: 'Duplicate media increased indexing and sync load.',
    referenceId: 'storage-indexing',
  }),
  rule({
    id: 'file_compression_high',
    category: 'File Compression',
    group: BEHAVIORAL,
    trigger: (metrics) => metrics.compressionTasks > thresholds.compressionTasks,
    notification: 'Compression tasks use heavy CPU.',
    recommendation: 'Batch tasks to reduce repeated load.',
    source: 'Source: CPU Power Studies',
    scoreImpact: -1,
    summary: 'Compression bursts added extra compute demand.',
    referenceId: 'cpu-power',
  }),
  rule({
    id: 'heavy_app_startups_high',
    category: 'Heavy App Startup Frequency',
    group: BEHAVIORAL,
    trigger: (metrics) => metrics.heavyAppOpens > thresholds.heavyAppOpens,
    notification: 'Heavy apps were opened many times today.',
    recommendation: 'Keep heavy apps open instead of reopening.',
    source: 'Source: App Startup CPU Research',
    scoreImpact: -2,
    summary: 'Repeated heavy app launches stacked CPU startup costs.',
    referenceId: 'app-lifecycle',
  }),
  rule({
    id: 'overcharging_high',
    category: 'Overcharging at 100%',
    group: CHARGING,
    trigger: (metrics) => metrics.timeAt100WhilePlugged > 20,
    notification: 'Phone stayed charging after reaching 100%.',
    recommendation: 'Unplug shortly after full.',
    source: 'Source: Battery University',
    scoreImpact: -3,
    summary: 'Time at full charge added avoidable energy waste.',
    referenceId: 'battery-university',
  }),
  rule({
    id: 'overcharging_positive',
    category: 'Overcharging at 100%',
    group: CHARGING,
    trigger: (metrics) => metrics.timeAt100WhilePlugged === 0,
    notification: 'Great charging habit today.',
    recommendation: 'Avoiding overcharge saves energy.',
    source: 'Source: Battery University',
    scoreImpact: 2,
    summary: 'No overcharging kept charging habits efficient.',
    referenceId: 'battery-university',
  }),
  rule({
    id: 'overnight_charging_high',
    category: 'Overnight Charging',
    group: CHARGING,
    trigger: (metrics) => metrics.chargingBetween00_06 > 240,
    notification: 'Your phone charged most of the night.',
    recommendation: 'Charge earlier in the evening.',
    source: 'Source: Battery Research',
    scoreImpact: -2,
    summary: 'Long overnight charging extended plugged-in time.',
    referenceId: 'battery-research',
  }),
  rule({
    id: 'frequent_charge_cycles_high',
    category: 'Frequent Charge Cycles',
    group: CHARGING,
    trigger: (metrics) => metrics.chargeSessions > 3,
    notification: 'Multiple charge cycles today.',
    recommendation: 'Longer, less frequent charges are more efficient.',
    source: 'Source: Battery Docs',
    scoreImpact: -2,
    summary: 'Frequent charge sessions added repeated charging overhead.',
    referenceId: 'battery-research',
  }),
  rule({
    id: 'fast_charging_high',
    category: 'Fast Charging',
    group: CHARGING,
    trigger: (metrics) => metrics.fastChargeSessions > 1,
    notification: 'Fast charging uses higher power peaks.',
    recommendation: 'Use normal speed when possible.',
    source: 'Source: Power Delivery Research',
    scoreImpact: -1,
    summary: 'Multiple fast-charge sessions increased power peaks.',
    referenceId: 'power-delivery',
  }),
  rule({
    id: 'charging_outside_zone_high',
    category: 'Charging Outside 20–80%',
    group: CHARGING,
    trigger: (metrics) => metrics.timeBelow20 + metrics.timeAbove80 > thresholds.batteryExtremeMinutes,
    notification: 'Battery spent significant time in extreme ranges.',
    recommendation: 'Try to stay in the 20–80% zone.',
    source: 'Source: Battery University',
    scoreImpact: -1,
    summary: 'Extended time in extreme charge ranges reduced charging efficiency.',
    referenceId: 'battery-university',
  }),
  rule({
    id: 'cpu_spikes_high',
    category: 'CPU Spikes',
    group: PROCESSING,
    trigger: (metrics) => metrics.cpuHighUsage > 10,
    notification: 'High CPU load increases energy use.',
    recommendation: 'Close unneeded heavy apps.',
    source: 'Source: CPU Energy Research',
    scoreImpact: -2,
    summary: 'Burst CPU load raised processing energy use.',
    referenceId: 'cpu-power',
  }),
  rule({
    id: 'background_compute_high',
    category: 'Background Compute',
    group: PROCESSING,
    trigger: (metrics) => metrics.backgroundComputeTime > metrics.backgroundComputeBaseline,
    notification: 'Background compute ran longer than usual.',
    recommendation: 'Reduce clutter to minimize indexing.',
    source: 'Source: OS Indexing Papers',
    scoreImpact: -2,
    summary: 'Background compute time exceeded the normal baseline.',
    referenceId: 'os-indexing',
  }),
  rule({
    id: 'navigation_usage_high',
    category: 'Navigation Usage',
    group: PROCESSING,
    trigger: (metrics) => metrics.navigationTime > 20,
    notification: 'Navigation uses GPS + screen + CPU heavily.',
    recommendation: 'Use navigation only when needed.',
    source: 'Source: Location Power Papers',
    scoreImpact: -3,
    summary: 'Navigation combined multiple high-demand systems.',
    referenceId: 'location-power',
  }),
  rule({
    id: 'camera_usage_high',
    category: 'Camera Usage',
    group: PROCESSING,
    trigger: (metrics) => metrics.cameraUsage > 10,
    notification: 'Camera consumes significant processing power.',
    recommendation: 'Shorter sessions reduce load.',
    source: 'Source: Image Processing Power Studies',
    scoreImpact: -2,
    summary: 'Extended camera use increased sensor and processing work.',
    referenceId: 'image-processing',
  }),
  rule({
    id: 'video_recording_4k_high',
    category: '4K Video Recording',
    group: PROCESSING,
    trigger: (metrics) => metrics.recorded4KVideo,
    notification: '4K video recording is extremely energy-intensive.',
    recommendation: 'Use high resolution only when necessary.',
    source: 'Source: Video Pipeline Energy Reports',
    scoreImpact: -4,
    summary: '4K recording heavily loaded the full media pipeline.',
    referenceId: 'video-pipeline',
  }),
  rule({
    id: 'gyroscope_heavy_usage_high',
    category: 'Gyroscope-heavy Usage',
    group: PROCESSING,
    trigger: (metrics) => metrics.gyroActiveApps > thresholds.gyroActiveApps,
    notification: 'Motion-heavy apps used sensors intensively.',
    recommendation: 'Limit long sessions.',
    source: 'Source: Sensor Energy Papers',
    scoreImpact: -1,
    summary: 'Motion-heavy apps kept sensors active for long stretches.',
    referenceId: 'sensor-energy',
  }),
  rule({
    id: 'ar_apps_high',
    category: 'AR Apps',
    group: PROCESSING,
    trigger: (metrics) => metrics.arAppUsage > 5,
    notification: 'AR requires camera + sensors + CPU.',
    recommendation: 'Short AR sessions reduce significant energy.',
    source: 'Source: AR Energy Studies',
    scoreImpact: -4,
    summary: 'AR combined camera, sensors, and compute into a heavy load.',
    referenceId: 'ar-energy',
  }),
  rule({
    id: 'proximity_sensor_high',
    category: 'Proximity Sensor',
    group: PROCESSING,
    trigger: (metrics) => metrics.proximityActiveTime > metrics.proximityBaseline * 2,
    notification: 'Call-related sensor activity was higher than usual.',
    recommendation: 'No major action needed — informative only.',
    source: 'Source: Telephony Sensor Docs',
    scoreImpact: -1,
    summary: 'Proximity sensor usage was above the day’s normal range.',
    referenceId: 'telephony-sensor',
  }),
  rule({
    id: 'face_id_ir_projector_high',
    category: 'FaceID IR Projector',
    group: PROCESSING,
    trigger: (metrics) => metrics.faceIDUnlocks > metrics.faceIDBaseline * 2,
    notification: 'Frequent unlocks activated the IR projector many times.',
    recommendation: 'Reduce unlock frequency where possible.',
    source: 'Source: Biometric Sensor Studies',
    scoreImpact: -1,
    summary: 'Frequent unlocks repeatedly activated secure sensing hardware.',
    referenceId: 'biometric-sensor',
  }),
  rule({
    id: 'radio_power_high',
    category: 'Radio Power (Low Signal Antenna Boost)',
    group: PROCESSING,
    trigger: (metrics) => metrics.radioHighPowerTime > thresholds.radioHighPowerTime,
    notification: 'The radio worked in high-power mode.',
    recommendation: 'Using Wi-Fi in low-signal areas helps.',
    source: 'Source: Mobile Radio Studies',
    scoreImpact: -3,
    summary: 'High-power radio mode increased antenna energy draw.',
    referenceId: 'mobile-radio-energy',
  }),
];
